[project]
name = "insights-core-messaging-workspace"
version = "0.0.0"
requires-python = ">= 3.11"

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
insights-core-messaging = { workspace = true }
insights-core-messaging-base = { workspace = true }
insights-core-messaging-kafka = { workspace = true }
insights-core-messaging-http = { workspace = true }

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["UP", "F632", "E", "W", "F", "I", "N", "B", "C4", "SIM"]
