[tox]
requires = tox-uv
envlist = py{311,312,313,314}

[testenv]
runner = uv-venv-lock-runner
extras = test
uv_sync_flags = --all-packages
commands =
    pytest -v --cov=insights_messaging --cov-branch --cov-report=term-missing
