name: Ruff

on:
  - push
  - pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python linter
        run: |
          pip install ruff
          ruff check .
