name: Tests

on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[testing]
      - name: Run tests
        run: pytest --cov=insights_messaging --cov-branch --cov-report=term-missing
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: ${{ matrix.python-version == '3.11' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
